### ISSUE TITLE
License file request

### ISSUE THREAD

**Issue by EvanHStanton** [pksunkara/pgx_ulid#19]
Hi there,

I noticed that the MIT/X11 license is mentioned in the README, but there are no corresponding files in the repo. We're interested in compiling this extension and publishing to a registry (pgt.dev), which requires the license to be bundled with the source material. May I ask whether making this file is an option?

Thank you.

**Comment by pksunkara** [comment]
Yup, I was just lazy to add that file. Feel free to send a PR with the author as "Pavan Kumar Sunkara"
