### ISSUE TITLE
where is rand()

### ISSUE THREAD

**Issue by orefalo** [pksunkara/pgx_ulid#29]
I am reading the code, of course, I am new to Rust.
and I can't find the random generation calls.

How/What do you use for random generation?

in cryptography, faster is not better - need to ensure you use a crypto ready random generator.

Thank you

**Comment by pksunkara** [comment]
We don't do the random generation ourselves but instead use the library `ulid`

**Comment by orefalo** [comment]
I see. let me check overthere if it's crypto secure.

btw, I finally got it compiling. neat extension, thank you
