### ISSUE TITLE
Commit Cargo.lock

### ISSUE THREAD

**Issue by tomhoule** [pksunkara/pgx_ulid#33]
There are valid reasons to disagree, but since this crate is more an artifact that is built and distributed than a library crate consumed as such, it would make sense to commit the Cargo.lock for reproducible builds. As a point of comparison, [timescaledb-toolkit](https://github.com/timescale/timescaledb-toolkit) is also a pgrx project, they commit their lock file. This question is coming from noticing how others do it, and because it's slightly inconvenient for nix packaging — definitely not a blocker though.

What do you think?

**Comment by pksunkara** [comment]
It must have been an oversight but yes, I agree with your logic.
