### ISSUE TITLE
Supporting prefixes for PULID

### ISSUE THREAD

**Issue by brettinternet** [pksunkara/pgx_ulid#48]
Hi, how feasible would it be to support a two-byte prefix to create a "PULID" - a prefixed ULID? The first 2 bytes encode the type of the entity such as table "users" having an ID of `UR01J2309A8G8NJ776A7XTPFRBG9`.

**Comment by pksunkara** [comment]
1. I don't intend to support anything like that in this project.
2. It should be pretty easy to change the existing code to do it if you fork it.
