### ISSUE TITLE
Request pg17 support

### ISSUE THREAD

**Issue by crunchyjohn** [pksunkara/pgx_ulid#51]
Hello!

I would like to request pg17 support for pgx_ulid.

When I build against PG17 using the latest released version (v0.1.5), I get the following error:

```
error: unexpected argument '--pg17' found

  tip: a similar argument exists: '--pg16'

Usage: cargo pgrx init <--pg11 <PG11>|--pg12 <PG12>|--pg13 <PG13>|--pg14 <PG14>|--pg15 <PG15>|--pg16 <PG16>|--base-port <BASE_PORT>|--base-testing-port <BASE_TESTING_PORT>|--configure-flag <CONFIGURE_FLAG>|--valgrind>

For more information, try '--help'.
```

Taking a quick look, I can see that at a minimum, PG17 needs to be added to the top level Cargo.toml file:

 * https://github.com/pksunkara/pgx_ulid/blob/master/Cargo.toml

I am unsure if more changes would be required.

Thanks!

**Comment by arjunyel** [comment]
pgrx just added PG17 support https://github.com/pgcentralfoundation/pgrx/releases/tag/v0.12.5

**Comment by pksunkara** [comment]
Looks like a few issues:

1. `postgresql-server-dev-17` seems to be missing for ubuntu arm.
2. Updating pgrx seemed to break the code and therefore needs fixes

**Comment by arjunyel** [comment]
Apologies if this isn't accurate but looks like there's an arm build on APT now https://packages.debian.org/trixie/postgresql-server-dev-17

**Comment by HRKings** [comment]
I've done some progress in updating the code, you can see the branch I'm using [here](https://github.com/pksunkara/pgx_ulid/compare/pg17...HRKings:pgx_ulid:pg17.).

I compiled it successfully, but I ran in the following error when installing the extension with pgrx: `Could not get shared object file 'ulid.so' from Cargo output.`

**Comment by HRKings** [comment]
After quite a bit of work, I managed to make it work in #54, many parts had to be rewritten so I understand if the PR is declined. In the meantime anyone can test/use my fork [here](https://github.com/HRKings/pgx_ulid/releases/tag/v0.2.0-rework) until pksunkara has the time to review the PR.

**Comment by gjtorikian** [comment]
Hi @pksunkara — sorry for the direct ping, but do you have an idea of when you’ll be able to review, merge, and release this patch to support PG17?

**Comment by pksunkara** [comment]
Reviewed the PR, hopefully should be able to get it out this month.

**Comment by gjtorikian** [comment]
Thanks for releasing this!

I just want to call out that I did need to change the name of the preloaded library: https://github.com/yettoapp/images/commit/5e1117413c4124fb0b200a306f7ecc9f7b9bb1cd#diff-5660d3b7ec1a6f794af3d79261aa1bd9f9a41ff9956869578d0e7eb50220f1d1R97

I hesitate to open a PR to fix this in the README because I’m not sure why (or how) the extension was renamed. But hopefully by leaving this comment someone in the future will stumble into it as a fix.

**Comment by pksunkara** [comment]
Yup, that was intentional because of underlying changes. Updating docs and README now.
